version: '3.8'

services:
  block-monitor-backend:
    build:
      context: .
      dockerfile: Dockerfile.native
    image: cardano/block-monitor-backend:latest
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx128m
      - QUARKUS_HTTP_HOST=0.0.0.0
      - QUARKUS_HTTP_PORT=8080
    volumes:
      - ./config:/work/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge