quarkus:
  application:
    name: block-monitor-backend
  http:
    port: 8080
    host: 0.0.0.0
  log:
    level: INFO
    console:
      json: false

  container-image:
    build: false
    group: cardano
    name: block-monitor-backend
    tag: ${quarkus.application.version:latest}
  native:
    builder-image: quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:jdk-24
  rest-client:
    name-com-api:
      url: https://api.name.com
    
monitor:
  primary:
    name: ${MONITOR_PRIMARY_NAME:localhost}
    host: ${MONITOR_PRIMARY_HOST:127.0.0.1}
    port: ${MONITOR_PRIMARY_PORT:8000}
  secondary:
    name: ${MONITOR_SECONDARY_NAME:localhost}
    host: ${MONITOR_SECONDARY_HOST:127.0.0.1}
    port: ${MONITOR_SECONDARY_PORT:8000}
  dns:
    api-base-url: ${DNS_API_BASE_URL:https://api.name.com}
    username: ${DNS_USERNAME:dummy-user}
    password: ${DNS_PASSWORD:dummy-password}
    domain: ${DNS_DOMAIN:example.com}
    record-id: ${DNS_RECORD_ID:dummy-id}
    record-host: ${DNS_RECORD_HOST:dummy-host}
    record-fqdn: ${DNS_RECORD_FQDN:dummy.example.com}
    record-type: ${DNS_RECORD_TYPE:A}
    record-ttl: ${DNS_RECORD_TTL:300}
  timing:
    check-interval: 60s
    failover-delay: 300s
    failback-delay: 600s
    connection-timeout: 10s


'%test':
  quarkus:
    log:
      console:
        json: false
"%test":
  quarkus:
    application:
      name: block-monitor-backend-test
    http:
      port: 8081
      host: localhost
    log:
      level: INFO
      console:
        json: false
    container-image:
      build: false
    rest-client:
      name-com-api:
        url: http://localhost:8082

  monitor:
    primary:
      name: test-primary
      host: 127.0.0.1
      port: 9001
    secondary:
      name: test-secondary
      host: 127.0.0.2
      port: 9002
    dns:
      api-base-url: http://localhost:8082
      username: test-user
      password: test-password
      domain: test.example.com
      record-id: "12345"
      record-host: test-record
      record-fqdn: test-record.test.example.com.
      record-type: A
      record-ttl: 60
    timing:
      check-interval: 10s
      failover-delay: 30s
      failback-delay: 60s
      connection-timeout: 2s
